apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepullbackoff-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepullbackoff-app
  template:
    metadata:
      labels:
        app: imagepullbackoff-app
    spec:
      containers:
        - name: imagepullbackoff-app
          image: fake-image-does-not-exist:latest