{
 "title": "Application Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"trading-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"trading-api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(trading_request_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "rate(trading_request_latency_seconds_sum[5m])\r\n/\r\nrate(trading_request_latency_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}