replicaCount: 3

image:
  repository: 985411011517.dkr.ecr.ap-southeast-1.amazonaws.com/cnrp-trading-api
  tag: "v1.0.0"

service:
  type: LoadBalancer

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 60